#pragma once

// ComponentTypes.h
#ifndef COMPONENT_TYPES_H
#define COMPONENT_TYPES_H

typedef enum {
	COMPONENT_TRANSFORM = 0,
	COMPONENT_RENDERABLE,
	COMPONENT_PHYSICS,
	COMPONENT_AUDIO,
	COMPONENT_SCRIPT,
	COMPONENT_COUNT,
	MAX_COMPONENT_TYPES,
} ComponentType;



#endif // !COMPONENT_TYPES_H
