#pragma once

#ifndef COMPONENT_TYPES_H
#define COMPONENT_TYPES_H

typedef enum {
    COMPONENT_TRANSFORM = 0,
    COMPONENT_RIGID_BODY,
    COMPONENT_GRAVITY,
    COMPONENT_COUNT,
} ComponentType;

#endif // COMPONENT_TYPES_H
